package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Passengers;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PassengersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASSENGERS
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    int deleteByPrimaryKey(Long passengerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASSENGERS
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    int insert(Passengers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASSENGERS
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    Passengers selectByPrimaryKey(Long passengerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASSENGERS
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    List<Passengers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASSENGERS
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    int updateByPrimaryKey(Passengers record);
}