package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Planes;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PlanesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANES
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANES
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    int insert(Planes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANES
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    Planes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANES
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    List<Planes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANES
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    int updateByPrimaryKey(Planes record);
}