package lt.vu.mybatis.model;

public class Passengers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PASSENGERS.PASSENGERID
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    private Long passengerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PASSENGERS.AGE
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PASSENGERS.LAST_NAME
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PASSENGERS.NAME
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PASSENGERS.PLANES_ID
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    private Long planesId;
    private Planes planes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PASSENGERS.PASSENGERID
     *
     * @return the value of PUBLIC.PASSENGERS.PASSENGERID
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public Long getPassengerid() {
        return passengerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PASSENGERS.PASSENGERID
     *
     * @param passengerid the value for PUBLIC.PASSENGERS.PASSENGERID
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public void setPassengerid(Long passengerid) {
        this.passengerid = passengerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PASSENGERS.AGE
     *
     * @return the value of PUBLIC.PASSENGERS.AGE
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PASSENGERS.AGE
     *
     * @param age the value for PUBLIC.PASSENGERS.AGE
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PASSENGERS.LAST_NAME
     *
     * @return the value of PUBLIC.PASSENGERS.LAST_NAME
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PASSENGERS.LAST_NAME
     *
     * @param lastName the value for PUBLIC.PASSENGERS.LAST_NAME
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PASSENGERS.NAME
     *
     * @return the value of PUBLIC.PASSENGERS.NAME
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PASSENGERS.NAME
     *
     * @param name the value for PUBLIC.PASSENGERS.NAME
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PASSENGERS.PLANES_ID
     *
     * @return the value of PUBLIC.PASSENGERS.PLANES_ID
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public Long getPlanesId() {
        return planesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PASSENGERS.PLANES_ID
     *
     * @param planesId the value for PUBLIC.PASSENGERS.PLANES_ID
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public void setPlanesId(Long planesId) {
        this.planesId = planesId;
    }
}