package lt.vu.mybatis.model;

public class Planes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANES.ID
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANES.AIRLINE
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    private String airline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANES.MODEL
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    private String model;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANES.ID
     *
     * @return the value of PUBLIC.PLANES.ID
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANES.ID
     *
     * @param id the value for PUBLIC.PLANES.ID
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANES.AIRLINE
     *
     * @return the value of PUBLIC.PLANES.AIRLINE
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public String getAirline() {
        return airline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANES.AIRLINE
     *
     * @param airline the value for PUBLIC.PLANES.AIRLINE
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public void setAirline(String airline) {
        this.airline = airline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANES.MODEL
     *
     * @return the value of PUBLIC.PLANES.MODEL
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANES.MODEL
     *
     * @param model the value for PUBLIC.PLANES.MODEL
     *
     * @mbg.generated Tue Apr 18 19:39:56 EEST 2023
     */
    public void setModel(String model) {
        this.model = model;
    }
}